apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podinfo-log-pvc
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteMany is not supported on minikube
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
